---
apiVersion: v1
kind: Service
metadata:
  namespace: frontend
  name: client-node-port-svc
  labels:
    task: client-node-port-svc
spec:
  ports:
    - name: client
      nodePort: 30001
      port: 3000
      targetPort: 3000
  selector:
    tier: client
  type: NodePort
