{{- if .Values.feAutoscaling.enabled}}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: frontend
  name: frontend-hpa
  labels:
    tier: client
spec:
  minReplicas: {{ .Values.feAutoscaling.minReplicas }}
  maxReplicas: {{ .Values.feAutoscaling.maxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend-deployment
  targetCPUUtilizationPercentage: {{ .Values.feAutoscaling.targetCPUPercentage }}
{{- end }}
